[package]
name = "hatch_os"
version = "0.1.0"
authors = ["Andrew Hatch <andrew@andrewhatch.net>"]
edition = "2018"

[profile.dev]
# we can't support stack unwinding, so just abort
panic = "abort"

[profile.release]
# we can't support stack unwinding, so just abort
panic = "abort"
